# Generated by Django 4.2.1 on 2023-08-28 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_category_listing_delete_auctionlisting'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='image_URL',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
