# Generated by Django 4.2.1 on 2023-08-30 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_watchlist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Watchlist',
        ),
    ]
