# Generated by Django 4.2.1 on 2023-10-07 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0015_alter_listing_watchlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='create_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
