# Generated by Django 4.2.1 on 2023-10-09 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0018_alter_listing_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='image_URL',
            field=models.CharField(max_length=1000),
        ),
    ]
