# Generated by Django 4.2.1 on 2023-10-09 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0020_bid_item_bid_price_bid_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='price',
            field=models.FloatField(),
        ),
    ]
