# Generated by Django 4.2.1 on 2023-10-09 12:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0021_alter_bid_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='content',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='posting_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 9, 12, 6, 14, 262892)),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
